---
title: "West Brook data intro"
author: "Evan Childress"
date: "10/27/2016"
output: html_document
---

##Overview
The data are presented in the structure that we have used for CJS models. With so many individuals and observations, we have found that complete matrices by individual get unwieldy, so the data are in a long format. The data are padded out for samples when a fish could have been caught but was not; the column "enc" can be used to filter for only fish that were caught. Letcher et al 2015 J of Animal Ecology should give you the necessary details for the sampling procedures. This is a rather cursory explanation, so please ask for clarification where necessary.

I am assuming you are using R. If you are not familiar with .rds files, you can read it like this:

```{r eval=F}
data<-readRDS("~/westBrookData.rds")
```

##Column explanations
###tag
PIT tag number, unique identifier

###cohort
year the fish was born, assigned based on size at initial capture and size distributions of fish of known age

###detectionDate
mostly self explanatory, but filled in for unobserved fish as the median capture date for all observed fish.

###sampleName
An ordered identifier for sampling mostly for recognition by people who did the sampling. This is not very clean because early in the study samples were not taken at stricly seasonal intervals. sampleNumber is probably more useful and intuitive.

###sampleNumber
A tidier identifier for samples that strictly increases by one for each season (4/yr)

###river
River the fish was observed in. NA if the fish was not observed.

####west brook
The mainstem

####wb jimmy
Larger tributary that fish can move back and forth into from WB section 31 (Open Large from Letcher et al 2015)

####wb mitchell 
Smaller tributary that fish can move back and forth into from WB section 35 (Open Small from Letcher et al 2015)

####wb obear
Smaller tributary that has a waterfall at its mouth, so fish can only move downstream into WB section 20 (Isolated Small from Letcher et al 2015)

###section
Indentifier for the 20m section that the fish was captured in. This is ordered from downstream to upstream starting at 1 within each river. 

###observedLength
in mm

###observedWeight
in g

###species
bkt = brook trout (native, self-sustained population)
bnt = brown trout (non-native, self-sustained population)
ats = atlantic salmon (stocked through 2005, no reproduction)

###enc
Logical, was the fish observed? (1 = yes, 0 = no)

###ageInSamples
number of seasons since summer of the year of birth (1st summer = 0)

###sampleIndex
sampleNumber rescaled to start at 1 and end at length(unique(sampleNumber)) for ease of looping in JAGS

###tagIndex
ordered, unique individual identifier 1:N

###year
of sample

###season
1 = spring, 2 = summer, 3 = fall, 4 = winter

###proportionSampled
Occasionally the sample was not complete (e.g., skipped west brook but did the tributaries). This is the proportion of sections in the river of capture that were sampled.

###knownZ
z is alive state, so this is 1 between first and last capture, and NA otherwise