column_map <- c(
	id = "ID", 
	line_number = "LINE_NO",
	drainage = "DRAINAGE",
	old_river = "RIVER",
	date = "DATE", 
	sample_type = "SAMPLE TYPE", 
	area = "AREA", 
	sample_name = "SAMPLE_NUM", 
	substrate = "SUBSTRATE",
	habitat = "HABITAT",
	river = "BRANCH", 
	section = "SECTION", 
	quarter = "QUARTER",
	pass = "PASS",
	effort = "EFFORT",
	time_of_capture = "TIME", 
	species = "SPECIES", 
	fish_number = "FISHNUMBER", 
	tag = "TAGNUMBER", 
	recapture_indicator = "RECAP", 
	cohort = "COHORT", 
	measured_length = "LENGTH", 
	measured_weight = "WEIGHT", 
	maturity = "MATURE", 
	sex = "SEX", 
	genetic_sample = "GENETICSAM", 
	scale_sample = "SCALESAMP",
	blood_sample = "BLOODSAMP",
	color = "COLOR",
	tint = "TINT",
	gill_biopsy = "GILL_BIOPS",
	previously_tagged = "SECOND_TAG",
	dead_on_capture = "MORTALITY", 
	number_of_pictures = "NO_OF_PICS",
	comments = "COMMENTS",
	comments2 = "COMMENTS2",
	acoustic_tag = "ACOUSTIC TAG NUMBER",
	acoustic_sn = "ACOUSTIC SN"
)

unknowns <- list(-9999, "-9999", "-9999\r\n-9999", "", -999, -99, -99999,"-9999.00","999.00",
                 "9999",9999, "np",-999.9,"-999.9",".9999","-999","-999.00","-999.90")
