column_map <- c(
	id = "ID", 
	line_number = "LINE_NO",
	drainage = "DRAINAGE",
	old_river = "RIVER",
	area = "AREA", 
	date = "DATE", 
	sample_type = "SAMPLE TYPE", 
  water_temperature = "WATER_TEMP",
	tide = "TIDE",
	salinity = "SALINITY",
	sample_name = "SAMPLE_NUM", 
	river = "BRANCH", 
	section = "SECTION", 
	quarter = "QUARTER",
	time_of_capture = "TIME", 
	datetime = "DATE/TIME",
	direction = "DIRECTION",
	species = "SPECIES", 
	fish_number = "FISHNUMBER", 
	tag = "TAGNUMBER", 
	recapture_indicator = "RECAP", 
	cohort = "COHORT", 
	measured_length = "LENGTH", 
	measured_weight = "WEIGHT", 
	maturity = "MATURE", 
	sex = "SEX", 
	genetic_sample = "GENETICSAM", 
	scale_sample = "SCALESAMP",
	previously_tagged = "SECOND_TAG",
	dead_on_capture = "MORTALITY", 
	comments = "COMMENTS",
	comments2 = "COMMENTS2",
	picutre = "PICTURE" 
)

unknowns <- list(-9999, "-9999", "-9999\r\n-9999", "", -999, -99, -99999,"-9999.00","999.00",
                 "9999",9999, "np",-999.9,"-999.9",".9999","-999","-999.00","-999.90")
