column_map <- c(
	 id = "ID", 
	 lavage = "Lavage", 
	 river = "River", 
	 date = "Date", 
	 survey = "Survey", 
	 area = "Area", 
	 sample_type = "Sample type", 
	 sample_name = "Sample Num",
	 substrate = "Substrate", 
	 habitat = "Habitat", 
	 braid = "Braid", 
	 section = "Section", 
	 pass = "Pass", 
	 effort = "Effort", 
	 species = "Species", 
	 fish_number = "Fishnumber", 
	 tag = "Tag number", 
	 recapture_indicator = "Recap", 
	 cohort = "Year of Stocking", 
	 measured_length = "Length", 
	 measured_weight = "Weight", 
	 sex = "Sex", 
	 maturity = "Mature", 
	 genetic_sample = "Genetic Sample", 
	 location = "Location", 
	 gill_biopsy = "Gill Biopsy", 
	 previously_tagged = "2nd tag", 
	 dead_on_capture = "Mortality", 
	 number_of_pictures = "NumPicts", 
	 time_of_capture = "Time", 
	 comments = "Comments"
)

unknowns <- list(-9999, "-9999", "-9999\r\n-9999", "", -999, -99, -99999,
                 "9999",9999, "np",-999.9,"-999.9",".9999","-999")
