column_map <- c(
	id = "ID1", 
	river = "RIVER", 
	date = "DATE", 
	survey = "SURVEY", 
	area = "AREA", 
	sample_type = "SAMPLE TYPE", 
	sample_name = "SAMPLE NUM", 
	substrate = "SUBSTRATE", 
	habitat = "HABITAT", 
	braid = "BRAID", 
	section = "SECTION", 
	pass = "PASS", 
	effort = "EFFORT", 
	species = "SPECIES", 
	fish_number = "FISHNUMBER", 
	tag = "TAG NUMBER", 
	recapture_indicator = "RECAP", 
	cohort = "YEAR OF STOCKING", 
	measured_length = "LENGTH", 
	measured_weight = "WEIGHT", 
	maturity = "MATURE", 
	sex = "SEX", 
	genetic_sample = "GENETICSAM", 
	location = "LOCATION", 
	gill_biopsy = "GILL BIOPSY", 
	previously_tagged = "SECOND TAG", 
	dead_on_capture = "MORTALITY", 
	number_of_pictures = "NOPICS", 
	time_of_capture = "TIME", 
	comments = "COMMENTS"
)
unknowns <- list(-9999, "-9999", "-9999\r\n-9999", "", -999, -99, -99999,
                 "9999",9999, "np",-999.9,"-999.9",".9999","-999")
